server:
  error:
    include-stacktrace: on-param
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animal?useSSL=false&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: update
